### ISSUE TITLE
Wrong Output 2016 Day 14 Part 2

### ISSUE THREAD

**Issue by vinaykapadia** [wildcardjoker/AdventOfCode#2]
Minor issue, but in 2016 Day 14 Part 2, you save and output the check hash and not the key hash.

    KeyList.Add(nextHash);
    Console.WriteLine(GenerateFoundKeyMessage(2, KeyList.Count, nextHash, index));

should be

    KeyList.Add(hash);
    Console.WriteLine(GenerateFoundKeyMessage(2, KeyList.Count, hash, _index));

**Comment by wildcardjoker** [comment]
Thanks, fixed!
